"""initial

Revision ID: 43748397b03f
Revises: acd1d3c390d7
Create Date: 2022-07-09 00:27:49.327894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43748397b03f'
down_revision = 'acd1d3c390d7'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('messages_user_read',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('message_id', sa.Integer(), nullable=True),
        sa.Column('message_is_read', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_user_read_id'), 'messages_user_read', ['id'], unique=False)
    op.create_table_comment(
        'messages_user_read',
        'Таблица соотвествия прочитанных сообшений пользователем(отметка о прочтении)',
        existing_comment=None,
        schema=None
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_id'), table_name='messages_user_read')
    op.drop_table('messages_user_read')
    # ### end Alembic commands ###
