version: "3.6"
services:
  postgres:
    image: postgres:14.2
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
        - djangonetwork
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - "./postgres:/var/lib/postgresql/data"
      - "./postgresql.conf:/etc/postgresql/postgresql.conf"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    env_file:
      - .env

  app:
    restart: always
    depends_on:
      - postgres
    links:
      - postgres:postgres
    networks:
      - djangonetwork
    build:
      context: app
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "${MESSENGER_PORT}:8080"
    volumes:
      - ./app:/app


networks:
  djangonetwork:
    driver: bridge